### PR TITLE
Gitlab provider

### PR DESCRIPTION
**Pull request by bscott**
First take at this, most of the code is from the Github provider, Gitlab API docs are not that great.

Thoughts?

### CODE REVIEW

**Comment by bscott** [comment]
Issue #31

**Comment by bscott** [comment]
Testing with GoWeb Example app

**Comment by bscott** [comment]
After Authorizing via Gitlab, when return to the redirect_uri of the GoWeb Example App, the following error is returned.

```
Error in auth/{provider}/callback - 0x3b00

gomniauth: Auth server responded with error 'Server replied with 404 Not Found.'.

*common.AuthServerError error in Handler 0xc20827bc80

auth/{provider}/callback - 0x3b00 
```

**Comment by matryer** [comment]
Is this ready to go in?

**Comment by bscott** [comment]
@matryer Yes I believe so

**Pull request merged**
